# Generated by Django 5.0 on 2025-02-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_text_1",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_2",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_3",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_4",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_5",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_6",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_7",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_8",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "output_text_9",
                    models.TextField(
                        blank=True,
                        help_text="Output text generated by the LLM",
                        null=True,
                    ),
                ),
                (
                    "doctor_remark",
                    models.TextField(help_text="Doctor's remark", null=True),
                ),
                (
                    "doctor_comment",
                    models.TextField(help_text="Doctor's comment", null=True),
                ),
                ("doctor_note", models.TextField(help_text="Doctor's note", null=True)),
                ("patient_mobile_number", models.CharField(max_length=15)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when the record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Time when the record was last updated"
                    ),
                ),
                (
                    "sensor_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patientdevicedata",
                    ),
                ),
            ],
        ),
    ]
