# Generated by Django 5.0 on 2025-02-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_llmoutput"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmoutput",
            name="history",
            field=models.TextField(
                blank=True, help_text="History of patient", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmoutput",
            name="symptoms",
            field=models.TextField(
                blank=True, help_text="Symptoms of patient", null=True
            ),
        ),
    ]
