# Generated by Django 5.0 on 2025-02-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_llmoutput_history_llmoutput_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmoutput",
            name="medication_type",
            field=models.CharField(
                blank=True, help_text="History of patient", max_length=255, null=True
            ),
        ),
    ]
