# Generated by Django 5.0 on 2025-03-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_llmoutput_medication_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdevicedata",
            name="o2_delta",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="patientdevicedata",
            name="rq",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
