# Generated by Django 5.0 on 2025-03-02 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_patientdevicedata_o2_delta_patientdevicedata_rq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="designation",
            new_name="medication",
        ),
    ]
