# Generated by Django 5.0 on 2025-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_llmoutput_file_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdevicedata",
            name="heart_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
