# Generated by Django 5.0 on 2025-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_patientdevicedata_heart_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmoutput",
            name="output_text_10",
            field=models.TextField(
                blank=True, help_text="Output text generated by the LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmoutput",
            name="output_text_11",
            field=models.TextField(
                blank=True, help_text="Output text generated by the LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmoutput",
            name="output_text_12",
            field=models.TextField(
                blank=True, help_text="Output text generated by the LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientdevicedata",
            name="hydrogen",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
