# Generated by Django 5.0 on 2025-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_llmoutput_output_text_10_llmoutput_output_text_11_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="device_serial_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
