# Generated by Django 5.0 on 2025-04-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_customuser_device_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmoutput",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes of doctor", null=True),
        ),
    ]
