# Generated by Django 5.0 on 2025-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_llmoutput_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
