# Generated by Django 5.0 on 2025-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_customuser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdevicedata",
            name="formaldehyde",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
