# Generated by Django 5.0 on 2025-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_patientdevicedata_formaldehyde"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdevicedata",
            name="formaldehyde",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
