# Generated by Django 5.0 on 2025-06-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_onetimepassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="device_serial_numbers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
